### ISSUE TITLE
Replace server config list with recursive table

### ISSUE THREAD

**Issue by Kefta** [AutoJukebox/serverhopper#2]
Removes repeat code, allows for more than 4 servers

**Comment by AutoJukebox** [comment]
Thanks for the idea, I'll add that in a bit.

**Comment by Kefta** [comment]
```
ServerList = {
   ["TTT"] = "127.0.0.1",
   ["Deathrun"] = "192.168.1.1",
}
```
Then, in the clientside, loop through the keys and add a button for each one.
